name: VoxelGamesLib-Dependencies
version: ${version.number}
main: com.voxelgameslib.dependencies.Dependencies
authors: [VoxelGamesLib]
depend: [ProtocolLib]
website: https://github.com/VoxelGamesLib/dependencies
api-version: 1.13
